name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
        
    - name: go-crossbuild-amd64
      uses: izumin5210/action-go-crossbuild@v1.0.0
      with:
        name: D2Lib
        arch: amd64
        os: darwin,linux,windows
